import type { Metadata } from "next";
import { SITE_NAME, SITE_URL } from "@/lib/site";

/** Absolute URL to the default Open Graph / social-share image. */
const DEFAULT_OG_IMAGE = `${SITE_URL}/opengraph-image`;
const DEFAULT_OG_IMAGE_ALT = `${SITE_NAME} — Instagram Story Viewer`;

export interface RobotsFlags {
  index?: boolean;
  follow?: boolean;
  noimageindex?: boolean;
  noarchive?: boolean;
  nosnippet?: boolean;
  notranslate?: boolean;
}

interface BuildMetadataArgs {
  title: string;
  description: string;
  /** Site-relative path starting with "/", e.g. "/about/" */
  path: string;
  /** The current locale's actual URL path for this page, if it differs from `path` (which stays the canonical, unprefixed lookup key). Falls back to `path` when omitted. */
  localizedPath?: string;
  /** Per-locale URLs for this same page, keyed by locale code plus "x-default"; rendered as `alternates.languages`. */
  languageAlternates?: Record<string, string>;
  ogImagePath?: string;
  noindex?: boolean;
  keywords?: string[];
  /** Overrides `title`/`description` for the og and twitter tags only, when they should read differently from the page title/meta description. */
  socialTitle?: string;
  socialDescription?: string;
  twitterSite?: string;
  twitterCreator?: string;
  /** Full control over robots directives; takes precedence over `noindex` when provided. */
  robots?: RobotsFlags;
  /** Absolute or site-relative canonical override; defaults to `${SITE_URL}${path}`. */
  canonicalUrl?: string;
  /** `og:locale` value for this page, e.g. from `getOgLocale(locale)`. Defaults to "en_US" when omitted. */
  ogLocale?: string;
}

function withTrailingSlash(path: string): string {
  if (path.match(/\.[a-zA-Z0-9]+$/)) return path; // Don't add trailing slash to files
  return path === "/" || path.endsWith("/") ? path : `${path}/`;
}

function resolveUrl(value: string): string {
  return value.startsWith("http") ? value : `${SITE_URL}${value}`;
}

/**
 * Normalises a page title:
 * 1. Resolves any `{siteName}` template variable left by translations
 * 2. Strips duplicate brand mentions ("InstaView Stories |", etc.)
 * 3. Strips common secondary keyword suffixes to reduce length
 * 4. Appends a single ` | SITE_NAME` suffix
 */
export function cleanTitle(rawTitle: string): string {
  let title = rawTitle.trim();

  // 1. Resolve {siteName} placeholder if present
  title = title.replace(/\{siteName\}/g, "InstaView Stories");

  // 2. Strip leading brand prefix ("InstaView Stories:" / "InstaViewStories:")
  title = title.replace(/^(InstaView\s*Stories|InstaViewStories)\s*:\s*/i, "");

  // 3. Strip brand mentions separated by pipes anywhere
  title = title.replace(/\s*\|\s*(InstaView\s*Stories|InstaViewStories)/gi, "");
  title = title.replace(/(InstaView\s*Stories|InstaViewStories)\s*\|\s*/gi, "");

  // 4. Strip common secondary keyword suffixes like "| Instagram Story Viewer"
  //    that push titles past 60 chars. These are redundant with the brand suffix.
  title = title.replace(/\s*\|\s*Instagram\s+Story\s+Viewer(?:\s+Support)?\s*$/i, "");

  // 5. Strip trailing "InstaView Stories" without pipe if duplicated
  title = title.replace(/\s+(InstaView\s*Stories|InstaViewStories)\s*$/i, "");

  title = title.trim();

  // 6. Append brand suffix if not already present
  if (!title.toLowerCase().endsWith(SITE_NAME.toLowerCase())) {
    title = `${title} | ${SITE_NAME}`;
  }

  return title;
}

export function cleanDescription(rawDescription: string): string {
  if (!rawDescription) return "";
  let desc = rawDescription.trim();
  desc = desc.replace(/\{siteName\}/g, "InstaView Stories");
  return desc;
}

export function buildMetadata({
  title: rawTitle,
  description: rawDescription,
  path,
  localizedPath,
  languageAlternates,
  ogImagePath,
  noindex,
  keywords,
  socialTitle,
  socialDescription,
  twitterSite,
  twitterCreator,
  robots,
  canonicalUrl,
  ogLocale,
}: BuildMetadataArgs): Metadata {
  const formattedTitle = cleanTitle(rawTitle);
  const formattedDescription = cleanDescription(rawDescription);
  const rawPath = localizedPath ?? path;
  const url = `${SITE_URL}${rawPath}`;
  const canonical = withTrailingSlash(canonicalUrl ? resolveUrl(canonicalUrl) : url);

  // OG image: use page-specific if provided, otherwise fall back to the
  // site-wide default generated by opengraph-image.tsx.
  const ogImage = ogImagePath ? resolveUrl(ogImagePath) : DEFAULT_OG_IMAGE;
  const ogImageAlt = DEFAULT_OG_IMAGE_ALT;

  const ogTitle = socialTitle ? cleanTitle(socialTitle) : formattedTitle;
  const ogDescription = socialDescription ? cleanDescription(socialDescription) : formattedDescription;

  const resolvedRobots = robots
    ? {
        index: robots.index ?? true,
        follow: robots.follow ?? true,
        ...(robots.noimageindex ? { noimageindex: true } : {}),
        ...(robots.noarchive ? { noarchive: true } : {}),
        ...(robots.nosnippet ? { nosnippet: true } : {}),
        ...(robots.notranslate ? { notranslate: true } : {}),
      }
    : { index: !noindex, follow: true };

  return {
    title: { absolute: formattedTitle },
    description: formattedDescription,
    ...(keywords && keywords.length > 0 ? { keywords } : {}),
    alternates: {
      canonical,
      ...(languageAlternates ? { languages: languageAlternates } : {}),
    },
    robots: resolvedRobots,
    openGraph: {
      title: ogTitle,
      description: ogDescription,
      url: canonical,
      siteName: SITE_NAME,
      type: "website",
      locale: ogLocale ?? "en_US",
      images: [{ url: ogImage, width: 1200, height: 630, alt: ogImageAlt }],
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description: ogDescription,
      images: [ogImage],
      ...(twitterSite ? { site: twitterSite } : {}),
      ...(twitterCreator ? { creator: twitterCreator } : {}),
    },
  };
}

